---
title: "課堂練習模版"
author: "趙士賢"
date: "2021-04-02"
output: output_format
params:
  id: "410573095"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 安裝/使用套件
```{r}
library(ggplot2)
install.packages()
```
## purl() 形成.R檔
```{r}
library(knitr)
purl()
```
## 創造物件 -> <- =
## .Last.value 最後的值

## 命名 .  _  letter number
## .開頭代表隱藏
```{r}
.fetter
fetter
`這是特殊命名`
```
## ls() 列出variables
## find("y") 找出變數在哪

## Atomic vector
```{r}
vnum <- 5
vnum1 <- c(2,vnum)
```
## 向量堆疊還是向量
```{r}
vec <- c(c(1,5),c(2,6))
```
```{r}
heightOfEntireClassroom <- c()
heightOfEntireClassroom <- sample(165:200,1)
```
## numeric , character , logic
```{r}
c(5,7)
c("Marry","Katty")
c(T,F,TRUE,FALSE)
```

```{r}
num1 <- 5 #非整數
num2 <- 5L#整數
typeof(num1)
typeof(num2)
num1Vector <- c(5,6,7)
num2Vector <- c(5L,6L,7L)
object.size(num1Vector)
object.size(num2Vector)
```

# string
# cat 顯示原字串
```{r}
char1 <- "你好"
char1 <- '你好'
dialogue <- c('小明說："明天不用上課"','你好')
cat(dialogue,sep = "\n")
```
# Atomic vector extended
## factor/time
## levels 查表
```{r}
majors10_char <- c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系')
typeof(majors10_char)
class(majors10_char)
majors10_factor <-factor( c('經濟學系','社會學系','社會學系','經濟學系','經濟學系','社會學系','經濟學系','經濟學系','經濟學系','社會學系'))
majors10_factor
typeof(majors10_factor)
class(majors10_factor)
levels(majors10_factor)
```
## as....() 轉型態
```{r}
a <- '1'
a <- as.numeric(a)
```












