---
title: "課堂練習模版"
author: "趙士賢"
date: "2021-03-30"
output: output_format
params:
  id: "410573095"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Your code

```{r}
AA = c(Mary=176, John=188, Jenny= 165, Kate=170)
LL = list(
  Mary=list(176,"Taipei"),
  John=list(188,"New Taipei"),
  Jenny=list(165,"Taichung"),
  Kate=list(170,"Hualien")
)
```
## [[1]] 取出值
## [1]   包含命名
```{r}
AA[1]
AA[[1]]
LL[1]
LL[[1]]
```
## 取多個
```{r}
AA[c(1,4)]
AA[c("Mary","Jenny")]
AA[c(T,F,T,T)]
```

## insert
```{r}
a <- c(4,5,7)
length(a)
a[[4]] <- 8
```
## 新增list data
```{r}
restaurant = "すき家 Sukiya (新北三峽店)"
date = lubridate::mdy("Nov 10, 2020")
order = list(
  list(
    item="蕃茄牛丼",
    quantity=1
  ) # 這裡少了一筆 "起司蕃茄牛丼"
)
total = 328
oneOrder <- list(
  "restaurant"=restaurant,
  "date"=date,
  "order"=order,
  "total"=total
)
# 找出不存在賦值
oneOrder[["order"]][[2]] = list(item="起司牛丼",quantity=1)
```
## 多筆新增
```{r}
a = c(3,5,7,9)
a[c(5,6)]=c(8,9)
print(a)
```
## 多筆新增list data
## 注意[]要包含parent layer結構
```{r}
currentNumberOfOrder <- length(oneOrder$order)
newOrderSeq <- 1:2 + currentNumberOfOrder
oneOrder$order[newOrderSeq] <- 
  list(
    list(
      item="牛丼飯",
      quantity=1
    ),
    list(
      item="豬排飯",
      quantity=1
    )
  )
View(oneOrder$order)
```
## 模版手法
```{r}
secondItem <- oneItem <- oneOrder$order[[1]]

oneItem$item <- "牛丼飯"
oneItem$quantity <- 1
secondItem$item <- "豬排飯"
secondItem$quantity <- 1

oneOrder$order[newOrders] <- list(
  oneItem, secondItem
)
```
## 替換
```{r}
library(lubridate)
LL0 <- LL <- list(
  "Mary was born on", 
  ymd("1995-7-1"),
  "John was born on",
  ymd("1997-10-27")
  )
LL[[2]] <- ymd("1995-06-19")
oneOrder$order[[2]][["quantity"]] = 2
LL[c(2,4)] <- list(ymd("1998-01-06"),ymd("1995-05-30"))
```
## 刪除
## 取出要的再存回自己
## 選不要的 -c(,)
```{r}
a <- c("l","k","z")
a <- a[c(1,3)]
print(a)
```
```{r}
a <- c("l","k","z")
a <- a[-c(1,3)]
print(a)
```
## list額外刪除方法
```{r}
LL <- list('a',T,183)
LL[c(1,3)] <- NULL
print(LL)
```
## names() 取出命名
```{r}
a0 <- a <- c(John=178, Mary=170, Hanson=180)
names(a)

names(a) <- c("John", "Kate", "Hason")
names(a)

a <- a0
names(a)[[2]] <- "May"
names(a)
```
## vector加減乘除
## elementwise
```{r}
a <- c(3,5,8)
b <- c(6,2,1)
a*b
a/b
a+b
a-b
```
## 餘數 %% 
```{r}
a <- sample(1:15 , 5 ,replace=T)
a%%2
```
## 次方 ** ^
```{r}
a ** b
```
## vector不等長時 , broadcast
## 把短的向量複製很多次
```{r}
a ** 3 == a ** c(3,3,3)
```
## 特例 len(a)=7 ; len(b)=5
## b broadcast兩次 切掉多餘部分
```{r}
set.seed(20857)
a <- sample(1:20 , 7 ,replace = T)
b <- sample(1:20 , 5 ,replace = T)
a**b
```
## paste0() 把字串黏在一起
```{r}
paste0(c("我叫"),c("小明","小美"))
paste0(c("我叫","我叫"),c("小明","小美"))
```






